apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 9.2.1
  http:
    service:
      spec:
        type: NodePort
        ports:
        - name: http
          port: 9200
          targetPort: 9200
          nodePort: 30092
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
